version: "3.9"

services:

  redis:
    image: redis:alpine3.12

  web:
    # user: 400:400
    build:
      context: ./services/web/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: "web"
    hostname: "webhost"
    # environment:
    #   fruit: "apple"
    env_file:
      - ./web.env
      - ./mysql.env
    volumes:
      - './services/web/:/usr/src/app/'
